using DotnetBazel.Core;

public static class RepositoryCommandOutput
{
    public static async Task WriteAsync(IEnumerable<INugetRepositoryEntry> entries, string name, TextWriter writer)
    {
        await writer.WriteLineAsync("\"Generated by dotnet2bazel\"");
        await writer.WriteLineAsync("");
        await writer.WriteLineAsync("load(\"@rules_dotnet//dotnet:defs.bzl\", \"nuget_repo\")");
        await writer.WriteLineAsync();
        await writer.WriteLineAsync($"def {name}():");
        await writer.WriteLineAsync("    \"rules_dotnet_dev_nuget_packages\"");
        await writer.WriteLineAsync("    nuget_repo(");
        await writer.WriteLineAsync($"        name = \"{name}\",");
        await writer.WriteLineAsync("        packages = [");
        foreach (var entry in entries)
        {
            await writer.WriteAsync($"            (\"{entry.Id}\", \"{entry.Version}\", \"{entry.Hash}\", [");

            var dependencies = entry.DependencyGroups.SingleOrDefault()?.Packages;
            if (dependencies != null)
            {
                await writer.WriteAsync(string.Join(", ", dependencies.Select(dep => $"\"{dep.Id}\"")));
            }

            var targetingPackOverrides = "";
            if (entry.RefItemGroups.Count > 0)
            {
                targetingPackOverrides = string.Join(", ", entry.TargetingPackOverrides.Select(item => $"\"{item}\""));
            }

            await writer.WriteLineAsync($"], [{targetingPackOverrides}]),");
        }
        await writer.WriteLineAsync("        ],");
        await writer.WriteLineAsync("    )");
    }
}

